version: '3.8'

#secrets:
#  ad1:
#      file: ./secrets/ad1.secret
#  ad2:
#      file: ./secrets/ad2.secret
secrets:
  ad1:
    environment: AD1_PASS
  ad2:
    environment: AD2_PASS

services:
  lab:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3050:3000/tcp
      - 880:80/tcp
      - 8443:443/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    labels:
      - flame.type=application
      - flame.name=AdGuard - Lab
      - flame.url=${AD1_URL}
      - flame.category=DNS
      - flame.icon=shield-account-outline
    networks:
      ipvlan_net:
        ipv4_address: ${AD1_IP}
  
  sync:
    image: ghcr.io/bakito/adguardhome-sync
    secrets:
      - ad1
      - ad2    
    command: run
    environment:
      LOG_LEVEL: 'info'
      ORIGIN_URL: ${AD1_HTTP}:80
      ORIGIN_USERNAME: ${AD_USERNAME}
      ORIGIN_PASSWORD: ${AD1_PASS}
      REPLICA_URL: ${AD2_HTTP}:80
      REPLICA_USERNAME: ${AD_USERNAME}
      REPLICA_PASSWORD: ${AD2_PASS}
      CRON: '*/5 * * * *' # run every 5 minutes
      RUNONSTART: true
      # Configure sync features; by default all features are enabled.
      # FEATURES_GENERALSETTINGS: true
      # FEATURES_QUERYLOGCONFIG: true
      # FEATURES_STATSCONFIG: true
      # FEATURES_CLIENTSETTINGS: true
      # FEATURES_SERVICES: true
      # FEATURES_FILTERS: true
      # FEATURES_DHCP_SERVERCONFIG: true
      # FEATURES_DHCP_STATICLEASES: true
      # FEATURES_DNS_SERVERCONFIG: true
      # FEATURES_DNS_ACCESSLISTS: true
      # FEATURES_DNS_REWRITES: true
    #volumes:
    #  - ./sync/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    networks:
      - monitor_adguard_sync
    ports:
      - ${API_PORT}:8080
    restart: unless-stopped

networks:
  monitor_adguard_sync:
    name: monitor_adguard_sync
    driver: bridge
  ipvlan_net:
    external: true

#secrets:
#  ad1:
#      file: ./secrets/ad1.secret
#  ad2:
#      file: ./secrets/ad2.secret

secrets:
  ad1:
    environment: AD1_PASS
  ad2:
    environment: AD2_PASS